// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FireGen from "./Fire.gen";

var make = FireGen.make;

var $$default = make;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* make Not a pure module */
