// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as IndexGen from "./Index.gen";

var make = IndexGen.make;

var TSApp = {
  make: make
};

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(make, {}), root);
}

export {
  TSApp ,
  
}
/* make Not a pure module */
