// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/legacy/ReactDOMRe.bs.js";
import * as IndexGen from "./Index.gen";

var make = IndexGen.make;

var TSApp = {
  make: make
};

ReactDOMRe.renderToElementWithId(React.createElement(make, {}), "root");

export {
  TSApp ,
  
}
/* make Not a pure module */
