// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function useState(prim) {
  return React.useState(function () {
              return Curry._1(prim, undefined);
            });
}

function useEffect2(prim0, prim1) {
  React.useEffect((function () {
          return Curry._1(prim0, undefined);
        }), prim1);
  
}

function $$setTimeout$1(prim0, prim1) {
  return setTimeout(prim0, prim1);
}

function $$clearTimeout$1(prim) {
  clearTimeout(prim);
  
}

function decrement(x) {
  return x - 1 | 0;
}

function $$default(interval, run, onFinished) {
  var match = React.useState(function () {
        return interval;
      });
  var setTimeToLaunch = match[1];
  var timeToLaunch = match[0];
  useEffect2((function (param) {
          if (!run) {
            return ;
          }
          if (timeToLaunch > 0) {
            var timerId = setTimeout((function (param) {
                    return Curry._1(setTimeToLaunch, decrement);
                  }), 1000);
            return (function (param) {
                      clearTimeout(timerId);
                      
                    });
          }
          Curry._1(onFinished, undefined);
          
        }), [
        timeToLaunch,
        run
      ]);
  return timeToLaunch;
}

export {
  useState ,
  useEffect2 ,
  $$setTimeout$1 as $$setTimeout,
  $$clearTimeout$1 as $$clearTimeout,
  decrement ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
