// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_List from "rescript/lib/es6/belt_List.js";

function not_(fn, x) {
  return !Curry._1(fn, x);
}

function expired(now, message) {
  return now > message.expires;
}

function nextExpire(messages) {
  return Belt_List.get(messages, 0);
}

function hook(param) {
  var match = React.useState(function () {
        return /* [] */0;
      });
  var setMessages = match[1];
  var messages = match[0];
  React.useEffect((function () {
          var nextTimeoutMilis = Belt_List.get(messages, 0);
          if (nextTimeoutMilis === undefined) {
            return ;
          }
          var timeoutId = setTimeout((function (param) {
                  return Curry._1(setMessages, (function (messages) {
                                var partial_arg = Date.now();
                                var partial_arg$1 = function (param) {
                                  return partial_arg > param.expires;
                                };
                                return Belt_List.keep(messages, (function (param) {
                                              return !Curry._1(partial_arg$1, param);
                                            }));
                              }));
                }), nextTimeoutMilis.expires - Date.now() | 0);
          return (function (param) {
                    clearTimeout(timeoutId);
                    
                  });
        }), [messages]);
  var addMessage = function (text) {
    return Curry._1(setMessages, (function (messages) {
                  return Belt_List.concat(messages, {
                              hd: {
                                expires: Date.now() + 3000,
                                text: text
                              },
                              tl: /* [] */0
                            });
                }));
  };
  return [
          Belt_List.toArray(messages),
          addMessage
        ];
}

var defaultTimeToLive = 3000;

export {
  defaultTimeToLive ,
  not_ ,
  expired ,
  nextExpire ,
  hook ,
  
}
/* react Not a pure module */
